services:
  - type: web
    name: llm-comparison-app
    env: docker
    rootDirectory: llm-comparison-app
    buildCommand: docker build -t llm-comparison-app .
    startCommand: docker run -p $PORT:3000 llm-comparison-app
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: "https://llm-comparison-sql-metrics.onrender.com"
      - key: VITE_OPENAI_API_KEY
        sync: false  # This will be set manually in Render dashboard for security
      - key: VITE_SQL_METRICS_EVALUATOR_API_URL
        value: "https://sql-metrics-evaluator.onrender.com"
      - key: PORT
        value: "3000"
    healthCheckPath: /
    autoDeploy: true 