version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sqleval
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - EXECUTION_TIMEOUT=5000
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn sql_metrics_evaluator.src.api:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sqleval
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: 